# Generated by Django 5.0.14 on 2025-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistmodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
